name: My First Workflow

on: push

jobs:
 first_job:
  - name: checkout Repo
    uses: actions/checkout@v4

  runs-on: ubuntu-latest
  steps:
  - name: Welcome message
    run: echno "My first Github action job"

  - name: List files
    run: ls

  - name: Read file
    run: cat README.md